# -*- coding: utf-8 -*-
"""tests_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zzHyKMGJZTsNZSSmI0QoJDCskbQ6dRd

## **MLE Sanity Tests**
"""

!git clone https://github.com/SSRajeshwari-13/ML-Final-Lab-Group-09.git

import joblib
import pandas as pd
from pathlib import Path


PROJECT_PATH = Path("ML-Final-Lab-Group-09")
SRC_PATH = PROJECT_PATH / "src"
DATA_PATH = PROJECT_PATH / "data" / "processed"


def test_model_can_be_loaded():
    model_path = SRC_PATH / "Final_model (1).pkl"

    model = joblib.load(model_path)

    assert model is not None
    print("✓ Model loaded successfully.")
    print("  Model type:", type(model).__name__)


def test_preprocessor_can_be_loaded():
    preprocessor_path = SRC_PATH / "preprocessing.pkl"

    preprocessor = joblib.load(preprocessor_path)

    assert preprocessor is not None
    print("\n✓ Preprocessor loaded successfully.")
    print("  Preprocessor type:", type(preprocessor).__name__)


def test_model_feature_count():
    model_path = SRC_PATH / "Final_model (1).pkl"

    model = joblib.load(model_path)

    assert hasattr(model, "n_features_in_")
    assert model.n_features_in_ == 61

    print("\n✓ Model feature count check passed.")
    print("  Model expects:", model.n_features_in_, "features")


def test_preprocessor_output_feature_count():
    preprocessor_path = SRC_PATH / "preprocessing.pkl"
    input_path = DATA_PATH / "sample_applicants_data.csv"

    preprocessor = joblib.load(preprocessor_path)
    input_data = pd.read_csv(input_path)

    transformed_data = preprocessor.transform(input_data)

    assert transformed_data.shape[1] == 61

    print("\n✓ Preprocessing feature count check passed.")
    print("  Transformed features:", transformed_data.shape[1])


def test_model_can_make_predictions():
    model_path = SRC_PATH / "Final_model (1).pkl"
    preprocessor_path = SRC_PATH / "preprocessing.pkl"
    input_path = DATA_PATH / "sample_applicants_data.csv"

    model = joblib.load(model_path)
    preprocessor = joblib.load(preprocessor_path)

    input_data = pd.read_csv(input_path)

    transformed_data = preprocessor.transform(input_data)

    transformed_data_df = pd.DataFrame(
        transformed_data,
        columns=preprocessor.get_feature_names_out()
    )

    predictions = model.predict(transformed_data_df)

    assert len(predictions) == len(input_data)

    print("\n✓ Prediction test passed.")
    print("  Number of predictions:", len(predictions))


def test_prediction_probabilities():
    model_path = SRC_PATH / "Final_model (1).pkl"
    preprocessor_path = SRC_PATH / "preprocessing.pkl"
    input_path = DATA_PATH / "sample_applicants_data.csv"

    model = joblib.load(model_path)
    preprocessor = joblib.load(preprocessor_path)

    input_data = pd.read_csv(input_path)

    transformed_data = preprocessor.transform(input_data)

    transformed_data_df = pd.DataFrame(
        transformed_data,
        columns=preprocessor.get_feature_names_out()
    )

    probabilities = model.predict_proba(transformed_data_df)

    assert probabilities.shape == (len(input_data), 2)
    assert ((probabilities >= 0) & (probabilities <= 1)).all()
    assert (probabilities.sum(axis=1) - 1 < 1e-6).all()

    print("\n✓ Probability test passed.")
    print("  Probability matrix shape:", probabilities.shape)


def test_input_columns_match_preprocessor():
    preprocessor_path = SRC_PATH / "preprocessing.pkl"
    input_path = DATA_PATH / "sample_applicants_data.csv"

    preprocessor = joblib.load(preprocessor_path)
    input_data = pd.read_csv(input_path)

    expected_columns = list(preprocessor.feature_names_in_)
    actual_columns = list(input_data.columns)

    assert actual_columns == expected_columns

    print("\n✓ Input column validation passed.")
    print("  Number of input columns:", len(actual_columns))


# Run all sanity checks
test_model_can_be_loaded()
test_preprocessor_can_be_loaded()
test_model_feature_count()
test_preprocessor_output_feature_count()
test_model_can_make_predictions()
test_prediction_probabilities()
test_input_columns_match_preprocessor()

print("\nAll sanity checks passed successfully.")