# -*- coding: utf-8 -*-
"""GROUP9(DATA_ANALYST).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-M7yiTfryeHGW0ZpFx_Pgu4C18uMIn6

**GROUP** **9**

CREDIT RISK PREDICTION
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

"""LOADING THE DATASET"""

import pandas as pd

url = "https://raw.githubusercontent.com/SSRajeshwari-13/ML-Final-Lab-Group-09/refs/heads/main/data/german_credit%20(1).csv"
df = pd.read_csv(url)

print(df)

"""PRINTS FIRST 5 ROWS"""

df.head()

"""PRINTS FIRST 5 COLUMNS

"""

df.tail()

"""FINDS THE DIMENSION OF THE DATASET"""

#gives the number of rows and columns present in the dataset
df.shape

"""SUMMARY STATISTICS"""

#used to give statistical summary of numerical columns
df.describe()

"""GIVES THE COLUMN NAMES IN THE DATASET"""

df.columns.tolist()

"""GIVES DATATYPE OF EACH COLUMN NAME"""

df.dtypes

"""DESCRIPTIVE STATISTICS"""

#used to give basic information about the dataset
df.info()

"""FINDS MISSING VALUES"""

#used to find missing values in each column
df.isnull().sum()

"""CHECKS FOR DUPLICATE"""

#used to find duplicate values in the dataset
df.duplicated().sum()

#used to drop the duplicate values from the dataset
df=df.drop_duplicates()
df

expected_columns = [
    'Checking_Status',
    'Duration_Months',
    'Credit_History',
    'Purpose',
    'Credit_Amount',
    'Savings_Status',
    'Employment_Since',
    'Installment_Rate',
    'Personal_Status_Sex',
    'Other_Debtors_Guarantors',
    'Residence_Since',
    'Property',
    'Age',
    'Other_Installment_Plans',
    'Housing',
    'Existing_Credits',
    'Job',
    'Dependents',
    'Telephone',
    'Foreign_Worker',
    'Credit_Risk'
]

print("Number of columns:", len(df.columns))

print("Missing expected columns:",
      set(expected_columns) - set(df.columns))

"""CHECKS FOR NUMERICAL COLUMNS"""

numeric_columns = [
    'Duration_Months',
    'Credit_Amount',
    'Installment_Rate',
    'Residence_Since',
    'Age',
    'Existing_Credits',
    'Dependents'
]

print(df[numeric_columns].describe())

"""CHECKS FOR IMPOSSIBLE AGE"""

print("Age below 18:", (df['Age'] < 18).sum())
print("Age above 100:", (df['Age'] > 100).sum())

"""CHECKS FOR INVALID CREDIT AMOUNT"""

print("Credit amount <= 0:",
      (df['Credit_Amount'] <= 0).sum())

"""CHECKS FOR INVALID DURATION"""

print("Duration <= 0:",
      (df['Duration_Months'] <= 0).sum())

"""CHECKS FOR OUTLIERS

IQR METHOD
"""

def find_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower) |
        (data[column] > upper)
    ]

    return outliers, lower, upper

for col in ['Credit_Amount', 'Duration_Months', 'Age']:
    outliers, lower, upper = find_outliers(df, col)

    print("\nColumn:", col)
    print("Lower limit:", lower)
    print("Upper limit:", upper)
    print("Number of outliers:", len(outliers))

"""SEPARATES FEATURES AND TARGET"""

X = df.drop('Credit_Risk', axis=1)

y = df['Credit_Risk']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

"""SPLITTING TRAIN AND TEST SET"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

"""IDENTIFYING CATEGORICAL VARIABLES"""

categorical_columns = X_train.select_dtypes(
    include=['object']
).columns

print("Categorical columns:")
print(list(categorical_columns))

"""IDENTIFYING NUMERICAL VARIABLES"""

numerical_columns = X_train.select_dtypes(
    include=['int64', 'float64']
).columns

print("Numerical columns:")
print(list(numerical_columns))

"""SCALING AND ONE HOT ENCODING"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_columns)
    ]
)

"""PREVENTS DATA LEAKAGE"""

#fit → learns the required information from the training data
#transform → applies scaling and one-hot encoding to the training data
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Training data processed successfully")
print("Testing data processed successfully")

"""CONVERTS PROCESSED DATA INTO DATAFRAMES"""

#converts the processed data back into a Pandas DataFrame and gives the columns proper names.
# 61 columns because one hot encoding has expanded the categorical columns
feature_names = preprocessor.get_feature_names_out()

X_train_processed = pd.DataFrame(
    X_train_processed,
    columns=feature_names
)

X_test_processed = pd.DataFrame(
    X_test_processed,
    columns=feature_names
)

print("Processed training data:", X_train_processed.shape)
print("Processed testing data:", X_test_processed.shape)

"""SAVING TEST AND TRAIN FILES"""

import os

print(os.getcwd())

import os
import pandas as pd

# Create processed folder
os.makedirs("data/processed", exist_ok=True)

# Add target column
train_data = X_train_processed.copy()
train_data["Credit_Risk"] = y_train.values

test_data = X_test_processed.copy()
test_data["Credit_Risk"] = y_test.values

# Save files
train_data.to_csv("data/processed/train.csv", index=False)
test_data.to_csv("data/processed/test.csv", index=False)

print("Train and test files saved successfully!")

print(os.listdir("data/processed"))

"""QUALITY LOG"""

#A Quality Log is basically a record of all the checks you performed on your dataset before giving it to the Machine Learning team.
quality_log = pd.DataFrame({
    'Check': [
        'Number of rows',
        'Number of columns',
        'Missing values',
        'Duplicate rows',
        'Training Set',
        'Testing  Set'
    ],
    'Result': [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(X_train),
        len(X_test)
    ]
})

print(quality_log)

"""SAVING DATA QUALITY LOG"""

quality_log.to_csv(
    "data/processed/data_quality_log.csv",
    index=False
)

print("Data quality log saved!")

"""LOADING CLEANED DATA"""

import pandas as pd

train_data = pd.read_csv("/content/data/processed/train.csv")
test_data = pd.read_csv("/content/data/processed/test.csv")

train_data

test_data

import os

os.makedirs("data/processed", exist_ok=True)

X_train_processed.to_csv(
    "data/processed/X_train_processed.csv",
    index=False
)

print("Training CSV saved successfully!")

X_test_processed.to_csv(
    "data/processed/X_test_processed.csv",
    index=False
)

print("Testing CSV saved successfully!")

import os

print(os.listdir("data/processed"))

import shutil
from google.colab import files

shutil.make_archive("cleaned_credit_data", "zip", "data/processed")

files.download("cleaned_credit_data.zip")

# ================================
# DATA ANALYST - EDA
# ================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv("/content/data/processed/train.csv")
test = pd.read_csv("/content/data/processed/test.csv")

target = "Credit_Risk"

print("Training data shape:", train.shape)
print("Testing data shape:", test.shape)

print("First 5 rows:")
display(train.head())

print("Column names:")
print(train.columns.tolist())

print("Statical Summary")
display(train.describe())

print(train.info())

target = "Credit_Risk"

print(train[target].value_counts())

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df,
    x="Credit_Risk"
)

plt.title("Distribution of Credit Risk")
plt.xlabel("Credit Risk Class")
plt.ylabel("Number of Applicants")

plt.show()

"""### Observation

The target variable is imbalanced, with Class 1 representing approximately 70% of observations and Class 2 approximately 30%.
Therefore, model evaluation should consider class-specific metrics such as precision, recall and F1-score rather than relying only on accuracy.
"""

numeric_columns = train.select_dtypes(include=np.number).columns
print("Number of numerical columns after encoding:",len(numeric_columns))

numeric_columns = [
    "num__Duration_Months",
    "num__Credit_Amount",
    "num__Installment_Rate",
    "num__Residence_Since",
    "num__Age",
    "num__Existing_Credits",
    "num__Dependents"
]

train[numeric_columns].hist(
    figsize=(18, 15),
    bins=20
)

plt.suptitle("Distribution of Numerical Features")
plt.tight_layout()
plt.show()

"""Key Finding: The numerical variables have different distribution shapes, with some showing noticeable skewness, while the one-hot encoded categorical variables are concentrated around 0 and 1. This indicates that the features have different levels of variability and should be interpreted according to their feature type during modelling.

Skewness Analysis
"""

numeric_columns = [
    "num__Duration_Months",
    "num__Credit_Amount",
    "num__Installment_Rate",
    "num__Residence_Since",
    "num__Age",
    "num__Existing_Credits",
    "num__Dependents"
]

skewness = train[numeric_columns].skew()

skewness_df = pd.DataFrame({
    "Feature": skewness.index,
    "Skewness": skewness.values
})

skewness_df = skewness_df.sort_values(
    by="Skewness",
    ascending=False
)

display(skewness_df)

plt.figure(figsize=(10, 5))

sns.barplot(
    data=skewness_df,
    x="Feature",
    y="Skewness"
)

plt.axhline(
    y=0,
    color="black",
    linestyle="--"
)

plt.title("Skewness of Numerical Features")
plt.xlabel("Feature")
plt.ylabel("Skewness")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""Key Finding: The highest absolute skewness occurs mainly in one-hot encoded categorical features, particularly cat__Purpose_A48 and cat__Purpose_A410. This reflects uneven category frequencies rather than necessarily indicating problematic data. Rare categories should therefore be considered carefully during subsequent modelling and feature interpretation.

Boxplots- Detect Possible anomalies
"""

plt.figure(figsize=(14, 7))

sns.boxplot(
    data=train[numeric_columns]
)

plt.title("Boxplot Analysis of Numerical Features")
plt.xlabel("Numerical Features")
plt.ylabel("Values")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""Key Finding: The boxplots reveal potential extreme observations in several numerical features, while one-hot encoded categorical variables are concentrated around 0 and 1. Potential numerical outliers should be investigated rather than automatically removed, as they may represent legitimate credit or customer characteristics.

Correlation analysis
"""

correlation_matrix = train[numeric_columns].corr()

plt.figure(figsize=(10, 7))

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0
)

plt.title("Correlation Heatmap of Numerical Features")

plt.tight_layout()
plt.show()

corr_pairs = (
    correlation_matrix
    .where(
        np.triu(
            np.ones(correlation_matrix.shape),
            k=1
        ).astype(bool)
    )
    .stack()
    .reset_index()
)

corr_pairs.columns = [
    "Feature_1",
    "Feature_2",
    "Correlation"
]

corr_pairs["Absolute_Correlation"] = (
    corr_pairs["Correlation"].abs()
)

corr_pairs = corr_pairs.sort_values(
    by="Absolute_Correlation",
    ascending=False
)

display(
    corr_pairs.head(10)
)

"""Key Finding: Most features have relatively weak pairwise correlations, but several encoded categorical variables show stronger relationships. This suggests some degree of feature redundancy, which should be considered during model development and interpretation.

Finding highly correlated features
"""

plt.figure(figsize=(8, 6))

sns.scatterplot(
    data=df,
    x="Age",
    y="Credit_Amount",
    hue="Credit_Risk",
    alpha=0.7
)

plt.title("Age vs Credit Amount by Credit Risk")
plt.xlabel("Age")
plt.ylabel("Credit Amount")

plt.show()

"""Feature interaction analysis"""

plt.figure(figsize=(8, 6))

sns.boxplot(
    data=df,
    x="Credit_Risk",
    y="Credit_Amount"
)

plt.title("Credit Amount by Credit Risk")
plt.xlabel("Credit Risk")
plt.ylabel("Credit Amount")

plt.show()

"""Key Finding: The two Credit Risk classes substantially overlap across Age and Credit Amount, indicating that these two variables alone do not clearly distinguish the classes. Their predictive contribution should therefore be evaluated together with other features during modelling.

Target vs important numerical feature
"""

plt.figure(figsize=(8, 6))

sns.boxplot(
    data=df,
    x="Credit_Risk",
    y="Duration_Months"
)

plt.title("Loan Duration by Credit Risk")
plt.xlabel("Credit Risk")
plt.ylabel("Duration in Months")

plt.show()

"""Key Finding: Class 2 has a slightly higher median and greater variability in Credit Amount than Class 1, with potential extreme observations present in both groups. However, substantial overlap remains, so Credit Amount should be considered alongside other features rather than used independently.

Find the features most correlated with the target
"""

plt.figure(figsize=(8, 6))

sns.countplot(
    data=df,
    x="Checking_Status",
    hue="Credit_Risk"
)

plt.title("Checking Status vs Credit Risk")
plt.xlabel("Checking Status")
plt.ylabel("Number of Applicants")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

target_correlation = (
    train[numeric_columns + ["Credit_Risk"]]
    .corr()["Credit_Risk"]
    .drop("Credit_Risk")
    .sort_values(
        key=abs,
        ascending=False
    )
)

print("Numerical features most associated with Credit Risk:")
display(target_correlation.to_frame("Correlation"))

"""# Top 3 Actionable Data Insights
### Insight 1 – Class Imbalance

The target variable is imbalanced, with approximately 70% of observations belonging to Class 1 and 30% belonging to Class 2.

**Action:** Model evaluation should use class-aware metrics such as precision, recall and F1-score in addition to accuracy. The class distribution should also be monitored during model development.

---

### Insight 2 – Checking Status and Credit Risk

Checking Status shows a noticeable relationship with Credit Risk, with some checking-status categories being more strongly associated with the target than others.

**Action:** Checking Status should be retained as an important categorical feature during model development and should be properly encoded before training.

---

### Insight 3 – Loan Duration and Credit Amount

Loan Duration and Credit Amount show useful relationships with credit risk. Credit Amount also exhibits substantial variation and potential extreme observations.

**Action:** These variables should be retained during modelling, while their distributions and extreme values should be monitored during preprocessing and model evaluation.

**Formulate Modeling Strategy**

load the processed train set and test set
"""

import pandas as pd

train_data = pd.read_csv("/content/data/processed/train.csv")
test_data = pd.read_csv("/content/data/processed/test.csv")

train_data

test_data

print("Train shape:", train_data.shape)
print("Test shape:", test_data.shape)

train.head()

"""Separate features and target"""

target = "Credit_Risk"

X_train = train_data.drop(columns=[target])
y_train = train_data[target]

X_test = test_data.drop(columns=[target])
y_test = test_data[target]

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nTarget classes:")
print(y_train.value_counts())

"""**The objective is to predict Credit Risk using supervised machine learning**.

The following classification algorithms will be evaluated:

1. Logistic Regression - baseline model
2. Decision Tree - interpretable non-linear model
3. Random Forest - ensemble model
4. Gradient Boosting - boosting-based candidate model

The models will be compared using:
- Accuracy
- Precision
- Recall
- F1-score
- Cross-validation score
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

print("Models imported successfully.")

"""Train the baseline model


* **Logistic Regression**



"""

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train, y_train)

print("Logistic Regression trained successfully.")

"""**Make Predications**"""

y_pred_logistic = logistic_model.predict(X_test)

print("Predictions generated successfully.")

print("\nFirst 20 predictions:")
print(y_pred_logistic[:20])

"""**Evaluate Logistic Regression**"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

accuracy = accuracy_score(y_test, y_pred_logistic)
precision = precision_score(y_test, y_pred_logistic, pos_label=2)
recall = recall_score(y_test, y_pred_logistic, pos_label=2)
f1 = f1_score(y_test, y_pred_logistic, pos_label=2)

print("Logistic Regression Results")
print("--------------------------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_logistic))

"""**Train Decision Tree**"""

decision_tree = DecisionTreeClassifier(
    random_state=42
)

decision_tree.fit(X_train, y_train)

y_pred_dt = decision_tree.predict(X_test)

print("Decision Tree trained successfully.")

"""**Evaluate**"""

accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, pos_label=2)
recall_dt = recall_score(y_test, y_pred_dt, pos_label=2)
f1_dt = f1_score(y_test, y_pred_dt, pos_label=2)

print("Decision Tree Results")
print("--------------------------------")
print("Accuracy :", accuracy_dt)
print("Precision:", precision_dt)
print("Recall   :", recall_dt)
print("F1 Score :", f1_dt)

"""**Train Random Forest**"""

random_forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

random_forest.fit(X_train, y_train)

y_pred_rf = random_forest.predict(X_test)

print("Random Forest trained successfully.")

"""**Evaluate**"""

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf, pos_label=2)
recall_rf = recall_score(y_test, y_pred_rf, pos_label=2)
f1_rf = f1_score(y_test, y_pred_rf, pos_label=2)

print("Random Forest Results")
print("--------------------------------")
print("Accuracy :", accuracy_rf)
print("Precision:", precision_rf)
print("Recall   :", recall_rf)
print("F1 Score :", f1_rf)

"""**Train Gradient Boosting**"""

gradient_boosting = GradientBoostingClassifier(
    random_state=42
)

gradient_boosting.fit(X_train, y_train)

y_pred_gb = gradient_boosting.predict(X_test)

print("Gradient Boosting trained successfully.")

"""**Evaluate**"""

accuracy_gb = accuracy_score(y_test, y_pred_gb)
precision_gb = precision_score(y_test, y_pred_gb, pos_label=2)
recall_gb = recall_score(y_test, y_pred_gb, pos_label=2)
f1_gb = f1_score(y_test, y_pred_gb, pos_label=2)

print("Gradient Boosting Results")
print("--------------------------------")
print("Accuracy :", accuracy_gb)
print("Precision:", precision_gb)
print("Recall   :", recall_gb)
print("F1 Score :", f1_gb)

"""Compare All Models


*   Logistic Regression
*   Decision Tree
*   Random Forest
*   Gradient Boosting




"""

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        accuracy,
        accuracy_dt,
        accuracy_rf,
        accuracy_gb
    ],
    "Precision": [
        precision,
        precision_dt,
        precision_rf,
        precision_gb
    ],
    "Recall": [
        recall,
        recall_dt,
        recall_rf,
        recall_gb
    ],
    "F1 Score": [
        f1,
        f1_dt,
        f1_rf,
        f1_gb
    ]
})

display(results.sort_values("F1 Score", ascending=False))

"""**Cross-validation**"""

from sklearn.model_selection import cross_val_score, StratifiedKFold

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

models = {
    "Logistic Regression": logistic_model,
    "Decision Tree": decision_tree,
    "Random Forest": random_forest,
    "Gradient Boosting": gradient_boosting
}

cv_results = []

for name, model in models.items():

    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="f1"
    )

    cv_results.append({
        "Model": name,
        "Mean CV F1": scores.mean(),
        "Std CV F1": scores.std()
    })

cv_table = pd.DataFrame(cv_results)

display(cv_table)

"""**Hyperparameter tuning**"""

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

gb_model = GradientBoostingClassifier(
    random_state=42
)

param_grid = {
    "n_estimators": [50, 100, 150],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [2, 3, 5],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

"""**Run GridSearchCV**"""

grid_search = GridSearchCV(
    estimator=gb_model,
    param_grid=param_grid,
    cv=cv,
    scoring="f1_macro",
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

"""**Find the best parameters**"""

print("Best Parameters:")
print(grid_search.best_params_)

"""**the best CV score**"""

print("Best Cross-Validation F1 Score:")
print(grid_search.best_score_)

"""**Get the tuned model**"""

best_gb_model = grid_search.best_estimator_

print(best_gb_model)

"""Evaluate on the test set"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

y_pred = best_gb_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average="macro"
)

recall = recall_score(
    y_test,
    y_pred,
    average="macro"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="macro"
)

print("Tuned Gradient Boosting Results")
print("--------------------------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print(classification_report(y_test, y_pred))

"""**Compare before and after tuning**"""

comparison = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],
    "Before Tuning": [
        0.79,
        0.68,
        0.566667,
        0.618182
    ],
    "After Tuning": [
        accuracy,
        precision,
        recall,
        f1
    ]
})

display(comparison)

"""**Feature Importances**"""

feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": best_gb_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    "Importance",
    ascending=False
)

display(feature_importance)

top_features = feature_importance.head(10)

plt.figure(figsize=(10, 6))

plt.barh(
    top_features["Feature"],
    top_features["Importance"]
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 10 Feature Importances - Gradient Boosting")
plt.gca().invert_yaxis()

plt.show()

import joblib

joblib.dump(
    best_gb_model,
    "final_gradient_boosting_model.pkl"
)

print("Final model saved successfully!")

import os

print(os.path.exists("final_gradient_boosting_model.pkl"))

print(type(best_gb_model))

import joblib

joblib.dump(
    best_gb_model,
    "/content/final_gradient_boosting_model.pkl"
)

print("Model saved successfully!")

import joblib

model = joblib.load("/content/final_gradient_boosting_model.pkl")

print(type(model))

import os

size = os.path.getsize("/content/final_gradient_boosting_model.pkl")

print("File size:", size, "bytes")

import joblib

model = joblib.load("/content/final_gradient_boosting_model.pkl")

print("Model loaded successfully!")
print(type(model))

