# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vd--5bHZ68rBXHcCYs3vNT_iy47e_gS

# **Machine Learning Engineer (MLE)**
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/SSRajeshwari-13/ML-Final-Lab-Group-09.git
# %cd ML-Final-Lab-Group-09

import pandas as pd
from pathlib import Path
import logging

data = [
    ["A11", 6, "A34", "A43", 1200, "A65", "A75", 1, "A93", "A101", 4, "A121", 23, "A143", "A152", 1, "A173", 1, "A191", "A201"],
    ["A14", 48, "A31", "A40", 8500, "A61", "A71", 4, "A92", "A101", 4, "A124", 61, "A142", "A152", 2, "A173", 1, "A191", "A201"],
    ["A13", 18, "A34", "A42", 3200, "A64", "A74", 2, "A93", "A101", 3, "A123", 42, "A141", "A152", 1, "A172", 1, "A192", "A201"],
    ["A12", 60, "A30", "A46", 9200, "A65", "A72", 4, "A91", "A103", 1, "A122", 30, "A142", "A153", 3, "A174", 2, "A192", "A201"],
    ["A11", 12, "A32", "A49", 2100, "A61", "A73", 3, "A92", "A101", 2, "A121", 27, "A143", "A152", 1, "A172", 1, "A191", "A202"],
    ["A13", 36, "A33", "A43", 6100, "A62", "A74", 4, "A93", "A101", 4, "A124", 47, "A143", "A151", 4, "A173", 2, "A191", "A201"],
    ["A12", 24, "A32", "A44", 4100, "A63", "A73", 2, "A92", "A102", 3, "A123", 38, "A142", "A152", 2, "A172", 3, "A192", "A201"],
    ["A14", 9, "A33", "A41", 1450, "A64", "A75", 1, "A93", "A101", 4, "A121", 68, "A141", "A151", 1, "A172", 1, "A191", "A201"],
    ["A11", 30, "A31", "A40", 5600, "A65", "A72", 3, "A91", "A103", 2, "A122", 25, "A142", "A153", 2, "A174", 1, "A192", "A201"],
    ["A13", 15, "A33", "A43", 2900, "A62", "A74", 2, "A92", "A101", 3, "A121", 44, "A143", "A152", 2, "A173", 1, "A191", "A202"],
]

columns = [
    "Checking_Status",
    "Duration_Months",
    "Credit_History",
    "Purpose",
    "Credit_Amount",
    "Savings_Status",
    "Employment_Since",
    "Installment_Rate",
    "Personal_Status_Sex",
    "Other_Debtors_Guarantors",
    "Residence_Since",
    "Property",
    "Age",
    "Other_Installment_Plans",
    "Housing",
    "Existing_Credits",
    "Job",
    "Dependents",
    "Telephone",
    "Foreign_Worker",
]

df = pd.DataFrame(data, columns=columns)

Path("data/processed").mkdir(parents=True, exist_ok=True)

output_file = "data/processed/sample_applicants_data.csv"
df.to_csv(output_file, index=False)

print(f"Saved successfully: {output_file}")
print("Shape:", df.shape)
display(df)

import logging

logger = logging.getLogger("MLE_Inference")
logger.setLevel(logging.INFO)

# Prevent duplicate log messages
logger.propagate = False

if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s - %(levelname)s - %(message)s"
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)

logger.info("Inference pipeline started.")

import joblib
import pandas as pd
import time

MODEL_PATH = "/content/ML-Final-Lab-Group-09/src/Final_model (1).pkl"
PREPROCESSOR_PATH = "/content/ML-Final-Lab-Group-09/src/preprocessing.pkl"
INPUT_PATH = "/content/ML-Final-Lab-Group-09/data/processed/sample_applicants_data.csv"

model = joblib.load(MODEL_PATH)
preprocessor = joblib.load(PREPROCESSOR_PATH)

input_df = pd.read_csv(INPUT_PATH)

print("Dataset shape:", input_df.shape)
print("Model type:", type(model))
print("Preprocessor type:", type(preprocessor))
print("Model classes:", model.classes_)

expected_columns = list(preprocessor.feature_names_in_)
actual_columns = list(input_df.columns)

print("Expected columns:")
print(expected_columns)

print("\nActual columns:")
print(actual_columns)

print("\nExact order match:", expected_columns == actual_columns)

print(
    "Missing columns:",
    sorted(set(expected_columns) - set(actual_columns))
)

print(
    "Extra columns:",
    sorted(set(actual_columns) - set(expected_columns))
)

start_time = time.perf_counter()

logger.info("Preprocessing started.")

try:
    transformed_data = preprocessor.transform(input_df)

    print("Preprocessing successful.\n")
    print("Raw input shape:", input_df.shape)
    print("Transformed output shape:", transformed_data.shape)
    print("Transformed data type:", type(transformed_data))

    logger.info("Preprocessing completed successfully.\n")

except Exception as error:
    print("Preprocessing failed.\n")
    print(type(error).__name__, ":", error)

    logger.error("Preprocessing failed: %s\n", error)

    raise

print("Model expects transformed features:", model.n_features_in_)
print("Preprocessor produced features:", transformed_data.shape[1])

if model.n_features_in_ == transformed_data.shape[1]:
    print("Success: preprocessor output matches model input.")
else:
    print("Warning: feature-count mismatch.")

transformed_data_df = pd.DataFrame(
    transformed_data,
    columns=preprocessor.get_feature_names_out()
)

predictions = model.predict(transformed_data_df)

probabilities = model.predict_proba(transformed_data_df)

logger.info("Prediction completed successfully.")

end_time = time.perf_counter()

latency = end_time - start_time

logger.info("Inference latency: %.3f ms", latency * 1000)
print(f"\nInference latency: {latency:.6f} seconds")
print(f"Inference latency: {latency * 1000:.3f} ms")

print("Predicted classes:")
print(predictions)

print("\nProbability matrix shape:")
print(probabilities.shape)

print("\nFirst applicant probability values:")
print(probabilities[0])

results = pd.DataFrame({
    "Sample": range(1, len(predictions) + 1),
    "Predicted_Class": predictions,
    "Class_1_Probability": probabilities[:, 0],
    "Class_2_Probability": probabilities[:, 1]
})

print("\nPrediction Results:")
print(results.to_string(index=False))

results = input_df.copy()

results["Predicted_Class"] = predictions
results["Probability_Class_1"] = probabilities[:, 0]
results["Probability_Class_2"] = probabilities[:, 1]
results["Prediction_Confidence"] = probabilities.max(axis=1)

results

output_path = "data/processed/prediction_results.csv"
results.to_csv(output_path, index=False)
print(f"\nPrediction results saved to: {output_path}")

