# -*- coding: utf-8 -*-
"""GROUP9(DATA ENGINEER).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAvIMQbpzV8MCbSGXE82dV8yOXWggowX

**GROUP** **9**

CREDIT RISK PREDICTION
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

"""LOADING THE DATASET"""

import pandas as pd

url = "https://raw.githubusercontent.com/SSRajeshwari-13/ML-Final-Lab-Group-09/refs/heads/main/data/german_credit%20(1).csv"
df = pd.read_csv(url)

print(df)

"""PRINTS FIRST 5 ROWS"""

df.head()

"""PRINTS FIRST 5 COLUMNS

"""

df.tail()

"""FINDS THE DIMENSION OF THE DATASET"""

#gives the number of rows and columns present in the dataset
df.shape

"""SUMMARY STATISTICS"""

#used to give statistical summary of numerical columns
df.describe()

"""GIVES THE COLUMN NAMES IN THE DATASET"""

df.columns.tolist()

"""GIVES DATATYPE OF EACH COLUMN NAME"""

df.dtypes

"""DESCRIPTIVE STATISTICS"""

#used to give basic information about the dataset
df.info()

"""FINDS MISSING VALUES"""

#used to find missing values in each column
df.isnull().sum()

"""CHECKS FOR DUPLICATE"""

#used to find duplicate values in the dataset
df.duplicated().sum()

#used to drop the duplicate values from the dataset
df=df.drop_duplicates()
df

expected_columns = [
    'Checking_Status',
    'Duration_Months',
    'Credit_History',
    'Purpose',
    'Credit_Amount',
    'Savings_Status',
    'Employment_Since',
    'Installment_Rate',
    'Personal_Status_Sex',
    'Other_Debtors_Guarantors',
    'Residence_Since',
    'Property',
    'Age',
    'Other_Installment_Plans',
    'Housing',
    'Existing_Credits',
    'Job',
    'Dependents',
    'Telephone',
    'Foreign_Worker',
    'Credit_Risk'
]

print("Number of columns:", len(df.columns))

print("Missing expected columns:",
      set(expected_columns) - set(df.columns))

"""CHECKS FOR NUMERICAL COLUMNS"""

numeric_columns = [
    'Duration_Months',
    'Credit_Amount',
    'Installment_Rate',
    'Residence_Since',
    'Age',
    'Existing_Credits',
    'Dependents'
]

print(df[numeric_columns].describe())

"""CHECKS FOR IMPOSSIBLE AGE"""

print("Age below 18:", (df['Age'] < 18).sum())
print("Age above 100:", (df['Age'] > 100).sum())

"""CHECKS FOR INVALID CREDIT AMOUNT"""

print("Credit amount <= 0:",
      (df['Credit_Amount'] <= 0).sum())

"""CHECKS FOR INVALID DURATION"""

print("Duration <= 0:",
      (df['Duration_Months'] <= 0).sum())

"""CHECKS FOR OUTLIERS

IQR METHOD
"""

def find_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower) |
        (data[column] > upper)
    ]

    return outliers, lower, upper

for col in ['Credit_Amount', 'Duration_Months', 'Age']:
    outliers, lower, upper = find_outliers(df, col)

    print("\nColumn:", col)
    print("Lower limit:", lower)
    print("Upper limit:", upper)
    print("Number of outliers:", len(outliers))

"""SEPARATES FEATURES AND TARGET"""

X = df.drop('Credit_Risk', axis=1)

y = df['Credit_Risk']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

"""SPLITTING TRAIN AND TEST SET"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

"""IDENTIFYING CATEGORICAL VARIABLES"""

categorical_columns = X_train.select_dtypes(
    include=['object']
).columns

print("Categorical columns:")
print(list(categorical_columns))

"""IDENTIFYING NUMERICAL VARIABLES"""

numerical_columns = X_train.select_dtypes(
    include=['int64', 'float64']
).columns

print("Numerical columns:")
print(list(numerical_columns))

"""SCALING AND ONE HOT ENCODING"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_columns)
    ]
)

"""PREVENTS DATA LEAKAGE"""

#fit → learns the required information from the training data
#transform → applies scaling and one-hot encoding to the training data
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Training data processed successfully")
print("Testing data processed successfully")

"""CONVERTS PROCESSED DATA INTO DATAFRAMES"""

#converts the processed data back into a Pandas DataFrame and gives the columns proper names.
# 61 columns because one hot encoding has expanded the categorical columns
feature_names = preprocessor.get_feature_names_out()

X_train_processed = pd.DataFrame(
    X_train_processed,
    columns=feature_names
)

X_test_processed = pd.DataFrame(
    X_test_processed,
    columns=feature_names
)

print("Processed training data:", X_train_processed.shape)
print("Processed testing data:", X_test_processed.shape)

"""SAVING TEST AND TRAIN FILES"""

import os

print(os.getcwd())

import os
import pandas as pd

# Create processed folder
os.makedirs("data/processed", exist_ok=True)

# Add target column
train_data = X_train_processed.copy()
train_data["Credit_Risk"] = y_train.values

test_data = X_test_processed.copy()
test_data["Credit_Risk"] = y_test.values

# Save files
train_data.to_csv("data/processed/train.csv", index=False)
test_data.to_csv("data/processed/test.csv", index=False)

print("Train and test files saved successfully!")

print(os.listdir("data/processed"))

"""QUALITY LOG"""

#A Quality Log is basically a record of all the checks you performed on your dataset before giving it to the Machine Learning team.
quality_log = pd.DataFrame({
    'Check': [
        'Number of rows',
        'Number of columns',
        'Missing values',
        'Duplicate rows',
        'Training Set',
        'Testing  Set'
    ],
    'Result': [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(X_train),
        len(X_test)
    ]
})

print(quality_log)

"""SAVING DATA QUALITY LOG"""

quality_log.to_csv(
    "data/processed/data_quality_log.csv",
    index=False
)

print("Data quality log saved!")

"""LOADING CLEANED DATA"""

import pandas as pd

train_data = pd.read_csv("/content/data/processed/train.csv")
test_data = pd.read_csv("/content/data/processed/test.csv")

train_data

test_data

import os

os.makedirs("data/processed", exist_ok=True)

X_train_processed.to_csv(
    "data/processed/X_train_processed.csv",
    index=False
)

print("Training CSV saved successfully!")

X_test_processed.to_csv(
    "data/processed/X_test_processed.csv",
    index=False
)

print("Testing CSV saved successfully!")

import os

print(os.listdir("data/processed"))

import shutil
from google.colab import files

shutil.make_archive("cleaned_credit_data", "zip", "data/processed")

files.download("cleaned_credit_data.zip")

